### ISSUE TITLE
美洽那边已经更新到了3.5.0，迁移 UIWebview 至 WKWebview，望更新下

### ISSUE THREAD

**Issue by bashen1** [Kennytian/meiqia-react-native#33]
美洽那边已经更新到了3.5.0，迁移 UIWebview 至 WKWebview，望更新下

**Comment by Kennytian** [comment]
@bashen1 @fangwei716 新版本已经发布至 npm 上 https://www.npmjs.com/package/meiqia-react-native/v/1.1.0

**Comment by bashen1** [comment]
@Kennytian 感谢，已经可以了
